name: Fix linting from a comment
on:
  issue_comment:
    types: [created]

jobs:
  fix:
    # Only run if comment is on a PR with the main repo, and if it contains the magic keywords
    if: >
      contains(github.event.comment.html_url, '/pull/') &&
      contains(github.event.comment.body, 'fix-linting') &&
      github.repository == 'adamrtalbot/nf-canary'
    runs-on: ubuntu-latest
    steps:
      # Use the @nf-core-bot token to check out so we can push later
      - uses: actions/checkout@v3

      # Action runs on the issue comment, so we don't get the PR by default
      # Use the gh cli to check out the PR
      - name: Checkout Pull Request
        run: gh pr checkout ${{ github.event.issue.number }}

      - uses: actions/setup-node@v3

      - name: Install Prettier
        run: npm install -g prettier @prettier/plugin-php

      # Check that we actually need to fix something
      - name: Run 'prettier --check'
        id: prettier_status
        run: |
          if prettier --check ${GITHUB_WORKSPACE}; then
            echo "result=pass" >> $GITHUB_OUTPUT
          else
            echo "result=fail" >> $GITHUB_OUTPUT
          fi

      - name: Run 'prettier --write'
        if: steps.prettier_status.outputs.result == 'fail'
        run: prettier --write ${GITHUB_WORKSPACE}

      - name: Commit & push changes
        if: steps.prettier_status.outputs.result == 'fail'
        run: |
          git config --global user.name 'adamrtalbot'
          git config --global user.email 'adamrtalbot@users.noreply.github.com'
          git commit -am "[automated] Fix linting with Prettier"
          git push
